baseurl: https://nnnewb.github.io/blog
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: weakptr's ç¬”è®°
timeZone: Asia/Shanghai

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: zh-cn
hasCJKLanguage: true

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon:

  footer:
    since: 2021
    customText: '<a href="https://beian.miit.gov.cn/">æµ™ICPå¤‡2021032371å·-1</a><span style="margin-left: 16px"></span><a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33032402002231" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="/image/beian.png" style="float:left;"/>æµ™å…¬ç½‘å®‰å¤‡ 33032402002231å·</a>'

  dateFormat:
    published: "2006å¹´ 1æœˆ 2æ—¥"
    lastUpdated: "2006å¹´ 1æœˆ 2æ—¥"

  sidebar:
    emoji: ğŸ‘
    subtitle: å¼ƒèˆ¹ï¼
    avatar:
      enabled: true
      local: true
      src: img/avatar.png

  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limits: 5
      - type: tag-cloud
        params:
          limits: 10
    page:
      - type: toc

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: false

    # Available values: auto, light, dark
    default: dark

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

  experiments:
    cms:
      server: https://weakptr.site/cms

  comments:
    enabled: false
    provider: vssue

    vssue:
      platform: github
      owner: nnnewb
      repo: blog
      clientId: 285910fdc1567a1a23e3
      clientSecret: f00da5438d9ac82c4a86024866c7a916ae411edc
      autoCreateIssue: false

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main:
    - identifier: home
      name: é¦–é¡µ
      url:
      weight: -100
      params:
        icon: home
        newTab: false
    - identifier: about
      name: å…³äºæˆ‘
      url: about
      weight: -90
      params:
        icon: user
    - identifier: "archive"
      name: å½’æ¡£
      url: "archive"
      weight: -70
      params:
        icon: "archives"
    - identifier: "categories"
      name: åˆ†ç±»
      url: "categories"
      weight: -60
      params:
        icon: hash
    - identifier: "tags"
      name: æ ‡ç­¾
      url: "tags"
      weight: -50
      params:
        icon: tag
    - identifier: "link"
      name: å‹é“¾
      url: "link"
      weight: -40
      params:
        icon: link
    - identifier: "search"
      name: æœç´¢
      url: "search"
      weight: -30
      params:
        icon: search
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/nnnewb/
      params:
        icon: brand-github

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
